export const PUBLIC_SITE_ROUTE_REFERENCE = [
  { path: "/", title: "Home", auth: "anonymous", index: true, availability: "available" },
  {
    path: "/search",
    title: "Search",
    auth: "anonymous",
    index: false,
    availability: "available",
  },
  {
    path: "/categories",
    title: "Categories",
    auth: "anonymous",
    index: true,
    availability: "available",
  },
  {
    path: "/categories/[slug]",
    title: "Category detail",
    auth: "anonymous",
    index: true,
    availability: "available",
  },
  {
    path: "/[slug]",
    title: "Server detail",
    auth: "anonymous",
    index: true,
    availability: "available",
  },
  {
    path: "/docs",
    title: "Documentation",
    auth: "anonymous",
    index: true,
    availability: "available",
  },
  {
    path: "/docs/api",
    title: "API docs",
    auth: "anonymous",
    index: true,
    availability: "planned",
  },
  {
    path: "/sign-in",
    title: "Publisher sign-in",
    auth: "anonymous",
    index: true,
    availability: "available",
  },
  {
    path: "/dashboard",
    title: "Publisher dashboard",
    auth: "authenticated",
    index: false,
    availability: "available",
  },
  {
    path: "/dashboard/listings/[id]",
    title: "Publisher listing detail",
    auth: "authenticated",
    index: false,
    availability: "available",
  },
] as const;